name: CI-CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabiogouw/datomic-starter:latest
            fabiogouw/datomic-starter:v${{ github.run_number }}
          build-args: |
            http_user=${{secrets.DATOMIC_HTTP_USER}}
            http_password=${{secrets.DATOMIC_HTTP_PASSWORD}}
            datomic_license=${{secrets.DATOMIC_LICENSE}}